# Generated by Django 5.2 on 2025-04-26 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_app', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
        migrations.AddField(
            model_name='income',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
    ]
